### ISSUE TITLE
Add support for production environment file

### ISSUE THREAD

**Issue by t-book** [GeoNode/geonode-project#152]
When starting geonode-project within docker, environment variables are populated from `.env`. In case somebody starts the stack for development and later in production everytime the .env file has to be updated accordingly. This ticket should discuss if the following can be improved (and hence added to the repository).

1) add an empty `.env-production` to the repository (and decide if it will by ignored by git or not)
2) add  `docker-compose-production.yml`  to the repository  with following content. (`.env_production` will be added after `.env` from `docker_compose.yml`

```
version: '2.2'
services:

  db:
    env_file:
        - .env_production

  geoserver:
    env_file:
        - .env_production

  django:
    env_file:
        - .env_production

  celery:
    env_file:
        - .env_production

  geonode:
    env_file:
        - .env_production

  letsencrypt:
    env_file:
        - .env_production
```

4. In case of going live one can leave the `.env` untouched and fill the `.env_production`:

```
SITEURL=http://example.com
GEOSERVER_WEB_UI_LOCATION=http://example.com/geoserver/
GEOSERVER_PUBLIC_LOCATION=http://example.com/geoserver/
GEONODE_LB_HOST_IP=http://example.com
HTTP_HOST=http://example.com
ACCOUNT_OPEN_SIGNUP=False
```

5. start the stack with: `docker-compose -f docker-compose.yml -f docker-compose-production.yml up -d`
