### ISSUE TITLE
data-dir-conf does nothing when mount is used instead of volume

### ISSUE THREAD

**Issue by frafra** [GeoNode/geonode-project#264]
https://github.com/GeoNode/geonode-project/blob/7393bb71b14691d4ce135d84fd3c1b1b0c9c2eb5/docker-compose.yml#L107-L113

Shouldn't look more like this?

```
 data-dir-conf: 
   image: geonode/geoserver_data:2.19.x 
   container_name: gsconf4${COMPOSE_PROJECT_NAME} 
    entrypoint: /bin/sh
    command: -c 'cp -r data /geoserver_data'
   volumes: 
     - geoserver-data-dir:/geoserver_data/data 
   restart: on-failure 
```

...or at least suggest running `data-dir-conf` once like that?

Otherwise, it looks like that the OAuth2 configuration will be missing:

```
geoserver4aza_geoportal | Configuration file '/geoserver_data/data'/security/auth/geonodeAuthProvider/config.xml is not available so it is gone to skip \n
geoserver4aza_geoportal | cp: cannot stat '/geoserver_data/data/security/role/geonode REST role service/config.xml': No such file or directory
```
