### ISSUE TITLE
Implement a CLI tool to guide in the creation of the .env file

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode-project#282]
The .env file has several repeated configurations, some with slightly different representation (domain with or without scheme, port, etc.).
Editing the .env file is error prone.

A cli tool to guide in the creation of the .env file would simplify the process and make it more robust.

### Features
- it should be a pure Python command, without any dependency outside Python builtins
- it will accept arguments and parameters either as: 
   - CLI arguments
   - JSON file
- it will use create the .env file starting from the .env.sample file
- it will overwrite the .env file on each run

### Parameters
 - required:
   - `hostname`, e.g. `master.demo.geonode.org`
 - optional:
   - `https` (boolean), default value is `False`
   - `email` - Admin email (this is required if https is set to True, since a valid email is required by Letsencrypt certbot)
   - `geonodepwd` - GeoNode admin password (required inside the .env)
   - `geoserverpwd` - Geoserver admin password (required inside the .env)
   - `pgpwd` - PostgreSQL password (required inside the .env)
   - `dbpwd` - GeoNode DB user password (required inside the .env)
   - `geodbpwd` - Geodatabase user password (required inside the .env)
   - `clientid` - Oauth2 client id (required inside the .env)
   - `clientsecret` - Oauth2 client secret (required inside the .env)

In case the optional (but required) parameters are missing, the tool will populate them with randomly generated strings.

The parameters can also be fed with a JSON file (a -f, --file option can be used to tell the CLI to use the file instead of arguments)

```json
{
	"hostname": ...,
	"https": ...,
	"email": ...,
	"geonodepwd": ...,
	"geoserverpwd": ...,
	"pgpwd": ...,
	"dbpwd": ...,
	"geodbpwd": ...,
	"clientid": ...,
	"clientsecret": ...,
} 
```

### .env substitutions
The .env.sample will have the following placeholders that will be replaced by the cli tool.

- POSTGRES_PASSWORD: `pgpwd`
- GEONODE_DATABASE_PASSWORD: `dbpwd`
- GEONODE_GEODATABASE_PASSWORD: `geodbpwd`
- DATABASE_URL: postgis://{GEONODE_DATABASE}:{`dbpwd`}@db:5432/{GEONODE_DATABASE}
- GEODATABASE_URL: postgis://{GEONODE_GEODATABASE}:{`geodbpwd`}@db:5432/{GEONODE_GEODATABASE}
- ALLOWED_HOSTS: "['django', '{`hostname`}', '*']"
- GEONODE_LB_HOST_IP: `hostname`
- HTTP_HOST: empty if `https` is True, otherwise `hostname`
- HTTPS_HOST: empty if `https` is False, otherwise `hostname`
- LETSENCRYPT_MODE: 'disabled' if https is False, otherwise 'production'
- GEOSERVER_WEB_UI_LOCATION: http(s)`hostname` (https if https is set to True)
- GEOSERVER_PUBLIC_LOCATION: http(s)`hostname` (https if https is set to True)
- GEOSERVER_ADMIN_PASSWORD: `geoserverpwd`
- ADMIN_PASSWORD: `geonodepwd`
- ADMIN_EMAIL: `email`
- OAUTH2_CLIENT_ID: `clientid`
- OAUTH2_CLIENT_SECRET: `clientsecret`

**Comment by frafra** [comment]
Interesting :) Just a couple of suggestions/notes:
1. Variable substitution can be achieved in `docker-compose.yml`, without writing any additional logic
2. Variables with conditionals (like `LETSENCRYPT_MODE`) could be simplified by improving the existing entrypoint
3. Crudini/python-dotenv can be used to set variables

Overall, simplifying the entrypoints and relying on existing compose features would make the management more robust, and it would also be beneficial for the development of a CLI tool/setup wizard, as it would be simpler to implement and maintain.

**Comment by giohappy** [comment]
@frafra I have considered variable substitutions with docker-compose, and enhancing the entrypoints (there are several places that need improvements and fixes) but we already rely on the .env file. How do you suggest avoiding generating it or relying on it?

**Comment by frafra** [comment]
@giohappy my suggestion would be to use both: an envfile to set the base variables, and the compose file to build upon them:

```
[frafra@e32 geonode]$ cat docker-compose.yml 
services:
  django:
    build: .
    environment:
      DATABASE_URL: postgis://${GEONODE_DATABASE}:${dbpwd}@db:5432/${GEONODE_DATABASE}
[frafra@e32 geonode]$ cat .env 
GEONODE_DATABASE=geonode
dbpwd=geonode
[frafra@e32 geonode]$ docker compose config
services:
  django:
    build:
      context: /tmp/geonode
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgis://geonode:geonode@db:5432/geonode
    networks:
      default: null
networks:
  default:
    name: geonode_default
[frafra@e32 geonode]$ dotenv set dbpwd newpass # pipx install python-dotenv[cli]
dbpwd=newpass
[frafra@e32 geonode]$ docker compose config
services:
  django:
    build:
      context: /tmp/geonode
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgis://geonode:newpass@db:5432/geonode
    networks:
      default: null
networks:
  default:
    name: geonode_default
```

Reference: https://docs.docker.com/compose/environment-variables/#substitute-environment-variables-in-compose-files

A setup wizard could be built on top, using python-dotenv for example: https://saurabh-kumar.com/python-dotenv/#getting-started
Using an envfile could also be beneficial for non-Docker user in my opinion, as such file could also be sourced in Bash and used to prepare an environment to launch Django commands, for example. Keeping Docker and non-Docker environments close could reduce code bloat and issues.
