### ISSUE TITLE
OSX Docker 502 Bad Gateway

### ISSUE THREAD

**Issue by t-book** [GeoNode/geonode-project#42]
Hi @afabiani,

Platform OSX 10.13.5
Docker Version 18.06.0-ce-mac70 (26399)

For a quick test of the new template under Docker I´ve run
<pre>
git clone https://github.com/GeoNode/geonode-project.git -b master
virtualenv ~/env/my_geonode
source ~/env/my_geonode/bin/activate
pip install Django==1.11.11
django-admin startproject --template=./geonode-project -e py,rst,json,yml,ini,env,sample -n Dockerfile my_geonode
cd my_geonode
docker-compose build --no-cache
docker-compose up -d
</pre>

All containers are running. I would expect that geonode is available at `http://localhost` as the Readme says. Unfortuantely I get a 502 Bad request.

<pre>nginx4           | 2018/08/09 09:36:59 [error] 6#6: *8 upstream prematurely closed connection while reading response header from upstream, client: 172.22.0.1, server: , request: "GET / HTTP/1.1", upstream: "http://172.22.0.3:8000/", host: "localhost"
</pre>

Do I miss to set some LB_HOST var? 

Thanks for you help,

Toni

**Comment by afabiani** [comment]
@t-book is this happening even after waiting some time? Usually it takes a bit before all containers have been fully started. Otherwise I'm afraid one or more of the django containers are failing somehow. You should be able to find the cause on the django4<geonode_project_something> container logs.

**Comment by t-book** [comment]
Hi @afabiani , yes unfortunately also when waiting some time. I´ll check the logs if I can find something ;) Thanks!

**Comment by dmarteau** [comment]
Same problem, no error reported in django container logs. 

Got the following from nginx:
```
geonode_1 | 2018/09/12 16:12:01 [error] 6#6: *1 upstream prematurely closed connection while
reading response header from upstream, client: 172.25.0.1, server: , request: "GET / HTTP/1.1", 
upstream: "uwsgi://172.25.0.2:8000", host: "192.168.0.6:8888"

geonode_1 | 172.25.0.1 - - [12/Sep/2018:16:12:01 +0000] "GET / HTTP/1.1" 502 173 "-" "Mozilla/5.0
 (Macintosh; Intel Mac OS X 10.11; rv:62.0) Gecko/20100101 Firefox/62.0" "-"
```
Ips are correct, but django in not accepting the connection (connection established but refused by django, I suspect a configuration problem.   

For information I can access the /geoserver

here is the configuration used:

```
version: "2"
services:

  db:
    image: geonode/postgis:9.6
    restart: unless-stopped
    stdin_open: true
    tty: true
    labels:
        org.geonode.component: db
        org.geonode.instance.name: geonode
        io.rancher.scheduler.affinity:host_label: geonodehost=<host label value>
    volumes:
      - dbdata:/var/lib/postgresql/data
      - dbbackups:/pg_backups
    environment:
      - GEONODE_DATABASE=geonode
      - GEONODE_DATABASE_PASSWORD=geonode
      - GEONODE_GEODATABASE=geonode_data
      - GEONODE_GEODATABASE_PASSWORD=geonode_data

  rabbitmq:
    image: rabbitmq
    restart: unless-stopped
    stdin_open: true
    tty: true
    labels:
        org.geonode.component: rabbitmq
        org.geonode.instance.name: geonode

  django:
    image: geonode/geonode:2.6.x
    restart: unless-stopped
    stdin_open: true
    tty: true
    labels:
        org.geonode.component: django
        org.geonode.instance.name: geonode
        io.rancher.scheduler.affinity:host_label: geonodehost=<host label value>
        io.rancher.container.pull_image: always
    depends_on:
      - db
      - rabbitmq
    command: django-admin.py runserver 0.0.0.0:8000 --settings=geonode.settings
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - GEONODE_INSTANCE_NAME=geonode
      - GEONODE_LB_HOST_IP=192.168.0.6
      - GEONODE_LB_PORT=8888
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - DEFAULT_BACKEND_DATASTORE=datastore
      - GEONODE_DATABASE=geonode
      - GEONODE_DATABASE_PASSWORD=geonode
      - GEONODE_GEODATABASE=geonode_data
      - GEONODE_GEODATABASE_PASSWORD=geonode_data
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - DJANGO_SETTINGS_MODULE=geonode.settings
      - ALLOWED_HOSTS=['django',]
      - DOCKER_ENV=production
      - UWSGI_CMD=uwsgi --ini /usr/src/app/uwsgi.ini
      - IS_CELERY=false
      - C_FORCE_ROOT=1
      - GEOSERVER_PUBLIC_LOCATION=http://geonode/geoserver/
      - GEOSERVER_LOCATION=http://geonode/geoserver/
      - SITEURL=http://geonode/

  celery:
    image: geonode/geonode:2.6.x
    restart: unless-stopped
    stdin_open: true
    tty: true
    labels:
        org.geonode.component: celery
        org.geonode.instance.name: geonode
        io.rancher.scheduler.affinity:host_label: geonodehost=<host label value>
        io.rancher.container.pull_image: always
    depends_on:
      - db
      - rabbitmq
    command: celery worker --app=geonode.celery_app:app -B -l INFO
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - GEONODE_INSTANCE_NAME=geonode
      - GEONODE_LB_HOST_IP=192.168.0.6
      - GEONODE_LB_PORT=8888
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - DEFAULT_BACKEND_DATASTORE=datastore
      - GEONODE_DATABASE=geonode
      - GEONODE_DATABASE_PASSWORD=geonode
      - GEONODE_GEODATABASE=geonode_data
      - GEONODE_GEODATABASE_PASSWORD=geonode_data
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - DJANGO_SETTINGS_MODULE=geonode.settings
      - ALLOWED_HOSTS=['django',]
      - DOCKER_ENV=production
      - CELERY_CMD=celery worker --app=geonode.celery_app:app -B -l INFO
      - IS_CELERY=true
      - C_FORCE_ROOT=1
      - GEOSERVER_PUBLIC_LOCATION=http://geonode/geoserver/
      - GEOSERVER_LOCATION=http://geonode/geoserver/
      - SITEURL=http://geonode/

  geoserver:
    image: geonode/geoserver:2.10.x
    restart: unless-stopped
    stdin_open: true
    tty: true
    labels:
        org.geonode.component: geoserver
        org.geonode.instance.name: geonode
        io.rancher.scheduler.affinity:host_label: geonodehost=<host label value>
        io.rancher.container.pull_image: always
    depends_on:
      - db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - geoserver-data-dir:/geoserver_data/data
    environment:
      - GEONODE_LB_HOST_IP=192.168.0.6
      - GEONODE_LB_PORT=8888
      - DOCKERHOST
      - GEONODE_HOST_IP
      - PUBLIC_PORT=80
      - DOCKER_HOST_IP

  geonode:
    image: geonode/nginx:geoserver
    restart: unless-stopped
    stdin_open: true
    tty: true
    labels:
        org.geonode.component: nginx
        org.geonode.instance.name: geonode
        io.rancher.scheduler.affinity:host_label: geonodehost=<host label value>
    depends_on:
      - django
      - geoserver
    ports:
      - "192.168.0.6:8888:80"

  data-dir-conf:
    image: geonode/geoserver_data:2.10.x
    restart: on-failure
    labels:
        org.geonode.component: conf
        org.geonode.instance.name: geonode
        io.rancher.scheduler.affinity:host_label: geonodehost=<host label value>
        io.rancher.container.start_once: 'true'
    command: /bin/true
    volumes:
      - geoserver-data-dir:/geoserver_data/data

volumes:

  geoserver-data-dir:
  dbdata:
  dbbackups:
```
